sudo: required
services:
  - docker

before_install:
  - docker build -t react-test -f ./client/dev.Dockerfile ./client

script:
  - docker run -e CI=true react-test npm test -- --coverage

after_success:
  - docker build -t sebasbeco/multi-client ./client
  - docker build -t sebasbeco/multi-nginx ./nginx
  - docker build -t sebasbeco/multi-server ./server
  - docker build -t sebasbeco/multi-worker ./worker

  # Log in to docker CLI
  - docker logout
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  # push the images to docker hub
  - docker push sebasbeco/multi-client
  - docker push sebasbeco/multi-nginx
  - docker push sebasbeco/multi-server
  - docker push sebasbeco/multi-worker
