sudo: required
services:
  - docker

before_install:
  - docker build -t react-test -f ./client/dev.Dockerfile ./client

script:
  - docker run -e CI=true react-test npm test -- --coverage

after_success:
  - docker build -t multi-client ./client
  - docker build -t multi-nginx ./nginx
  - docker build -t multi-server ./server
  - docker build -t multi-worker ./worker

  # Log in to docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  # push the images to docker hub
  - docker push multi-client
  - docker push multi-nginx
  - docker push multi-server
  - docker push multi-worker
