version: '3.7'

services:
  postgres:
    image: postgres:10
    environment:
      - POSTGRES_PASSWORD=postgres_password
  redis:
    image: redis:4
  nginx:
    restart: always
    build:
      context: nginx
      dockerfile: dev.Dockerfile
    ports:
      - 3050:80
  api:
    build:
      context: server
      dockerfile: dev.Dockerfile
    volumes:
      - /app/node_modules  # don't overwrite the node_modules folder in the container
      - ./server:/app
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - PGUSER=postgres
      - PGHOST=postgres
      - PGDATABASE=postgres
      - PGPASSWORD=postgres_password
      - PGPORT=5432
  client:
    stdin_open: true
    build:
      context: client
      dockerfile: dev.Dockerfile
    volumes:
      - /app/node_modules
      - ./client:/app
  worker:
    build:
      context: worker
      dockerfile: dev.Dockerfile
    volumes:
      - /app/node_modules
      - ./worker:/app
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
